// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecnusAPI.Data;

#nullable disable

namespace TecnusAPI.Migrations
{
    [DbContext(typeof(TecnusDBContext))]
    [Migration("20250604115649_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TecnusAPI.Models.CursoModel", b =>
                {
                    b.Property<int>("Id_Curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Curso"));

                    b.Property<float>("Descricao_Curso")
                        .HasMaxLength(800)
                        .HasColumnType("real");

                    b.Property<string>("Duracao_Curso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome_Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Professor_Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Curso");

                    b.ToTable("Tbl_Curso");
                });

            modelBuilder.Entity("TecnusAPI.Models.FeedbackModel", b =>
                {
                    b.Property<int>("Id_Feedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Feedback"));

                    b.Property<string>("Assunto_Feedback")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Aula_Feedback")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Curso_Feedback")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome_Feedback")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Feedback");

                    b.ToTable("Tbl_Feedback");
                });

            modelBuilder.Entity("TecnusAPI.Models.PerguntaModel", b =>
                {
                    b.Property<int>("Id_Pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pergunta"));

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id_Pergunta");

                    b.HasIndex("QuizId");

                    b.ToTable("Tbl_Pergunta");
                });

            modelBuilder.Entity("TecnusAPI.Models.QuizModel", b =>
                {
                    b.Property<int>("Id_Quiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Quiz"));

                    b.Property<string>("Titulo_Quizz")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Quiz");

                    b.ToTable("Tbl_Quiz");
                });

            modelBuilder.Entity("TecnusAPI.Models.RespostaModel", b =>
                {
                    b.Property<int>("Id_Resposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Resposta"));

                    b.Property<bool>("Correta")
                        .HasColumnType("bit");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id_Resposta");

                    b.HasIndex("PerguntaId");

                    b.ToTable("Tbl_Resposta");
                });

            modelBuilder.Entity("TecnusAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("CEP_Usuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CPF_Usuario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Complemento_Usuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email_Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco_Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome_Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Senha_Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone_Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Tbl_Usuario");
                });

            modelBuilder.Entity("TecnusAPI.Models.VideoModel", b =>
                {
                    b.Property<int>("Id_Video")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Video"));

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id_Video");

                    b.ToTable("Tbl_Video");
                });

            modelBuilder.Entity("TecnusAPI.Models.VisualizacaoVideoModel", b =>
                {
                    b.Property<int>("Id_Visualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Visualizacao"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<int>("TempoAssistidoSegundos_Visualizacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ultima_Visuailizacao")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioId_Visualizacao")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("VideoId_Visualizacao")
                        .HasColumnType("int");

                    b.HasKey("Id_Visualizacao");

                    b.HasIndex("VideoId_Visualizacao");

                    b.HasIndex(new[] { "UsuarioId_Visualizacao", "VideoId_Visualizacao" }, "IX_Visualizacoes_UsuarioVideo");

                    b.ToTable("VisualizacoesVideos", (string)null);
                });

            modelBuilder.Entity("TecnusAPI.Models.PerguntaModel", b =>
                {
                    b.HasOne("TecnusAPI.Models.QuizModel", "Quiz")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TecnusAPI.Models.RespostaModel", b =>
                {
                    b.HasOne("TecnusAPI.Models.PerguntaModel", "Pergunta")
                        .WithMany("Respostas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("TecnusAPI.Models.VisualizacaoVideoModel", b =>
                {
                    b.HasOne("TecnusAPI.Models.VideoModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId_Visualizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TecnusAPI.Models.PerguntaModel", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("TecnusAPI.Models.QuizModel", b =>
                {
                    b.Navigation("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
